#!/bin/bash

cmd=$1
n=$2

if [ "$cmd" == "start" ];then
if [ -f "zoo.running" ];then
	./run_zoo stop $(cat "zoo.running")
	run "zoo.running"
fi

conf_file="zoo.cfg"
echo -e "tickTime=2000\n"\
"dataDir=/home/jianyu/zookeeper-3.4.6/data/\n"\
"clientPort=2182\n"\
"initLimit=10\n"\
"syncLimit=5\n" > $conf_file

ip_list=("10.22.1.1" "10.22.1.2" "10.22.1.3" "10.22.1.4" "10.22.1.5" "10.22.1.6" "10.22.1.7" "10.22.1.8" "10.22.1.9")

k_list=$(seq $n)

for i in $k_list
do
	echo "server."$i"=""${ip_list[i - 1]}"":2667:3667" >> $conf_file
done

./scp_multi $conf_file zookeeper-3.4.6/conf $n
./run_multi "rm ~/consensus.zoo.log;rm ~/wait.zoo.log" $n
./run_multi "mkdir ~/zookeeper-3.4.6/data" $n
./run_multi "echo \$((\$i + 1)) > ~/zookeeper-3.4.6/data/myid" $n
./run_multi "~/zookeeper-3.4.6/bin/zkServer.sh start" $n

sleep 3
leader_ip=${ip_list[0]}
for i in $k_list
do
	status=$(ssh -t jianyu@"${ip_list[i]}" "~/zookeeper-3.4.6/bin/zkServer.sh status"|grep leader|wc -l)
	if [ "$status" == "1" ];then
		leader_ip=${ip_list[i]}
	fi
done
echo "leader ip is "$leader_ip
echo $n > zoo.running
if [ ! -d "result" ];then
mkdir result
fi

if [ ! -d result/$n ];then
mkdir result/$n
fi

log_file="result/"$n"/"$(date +%s)".txt"

r=$(seq $3)
for g in $r
do
PYTHONPATH=~/zk-smoketest/lib.linux-x86_64-2.6 LD_LIBRARY_PATH=~/zk-smoketest/lib.linux-x86_64-2.6 ~/zk-smoketest/zk-latencies.py --servers=$leader_ip":2182" --znode_size=64 --znode_count=10000 --synchronous --root_znode=/zk-latencies$g &
done
PYTHONPATH=~/zk-smoketest/lib.linux-x86_64-2.6 LD_LIBRARY_PATH=~/zk-smoketest/lib.linux-x86_64-2.6 ~/zk-smoketest/zk-latencies.py --servers=$leader_ip":2182" --znode_size=64 --znode_count=10000 --synchronous --root_znode=/zk-latencies8

ssh -t jianyu@$leader_ip "cat ~/consensus.zoo.log" > "/home/jianyu/consensus.zoo."$n".log"
ssh -t jianyu@$leader_ip "cat ~/wait.zoo.log" > "/home/jianyu/wait.zoo."$n".log"
./run_zoo stop $n
exit
fi

if [ "$cmd" == "stop" ];then
~/zookeeper-3.4.6/bin/zkServer.sh stop
./run_multi "~/zookeeper-3.4.6/bin/zkServer.sh stop" $n
rm "zoo.running"
fi


