#!/bin/bash
#scp_multi file remote_path n

file=$1
remote=$2
n=$3
server_count=$(( $n - 1 ))
ip_list=("10.22.1.2" "10.22.1.3" "10.22.1.4" "10.22.1.5" "10.22.1.6" "10.22.1.7" "10.22.1.8" "10.22.1.9")

user="jianyu"
k_list=$(seq $server_count)

for i in $k_list
do
	echo "transfer file to ""${ip_list[i - 1]}"
	scp "$file" $user@"${ip_list[i - 1]}":/home/$user/$remote/
done
cp $file /home/$user/$remote/ -f

